---

  - name: Create directory for web
    file: 
      path: /home/ubuntu/web
      state: directory

  - name: Copy files
    become: true
    copy:
      src: /root/project/backend.tar.gz
      dest: /home/ubuntu

  - name: Unarchive backend files
    unarchive:
      src: /home/ubuntu/backend.tar.gz
      dest: /home/ubuntu/web
      copy: no

  - name: Start backend
    become: true
    shell: |
      cd /home/ubuntu/web
      npm install
      pm2 stop default
      echo "List before launching"
      pm2 list
      pm2 start npm -- start
      echo "List after launching"
      pm2 list
      sleep 30
      echo "Check if the application is still up after 30s"
      pm2 list

  - name: Wait for 60 seconds
    pause:
      seconds: 60