---

  - name: Create directory for backend
    become: true
    file: 
      path: /home/ubuntu/web
      state: directory
      mode: 0755

  - name: Copy files
    become: true
    copy:
      src: /home/circleci/project/backend.tar.gz
      dest: /home/ubuntu

  - name: Unarchive backend files
    unarchive:
      src: /home/ubuntu/backend.tar.gz
      dest: /home/ubuntu/web
      copy: no

  - name: Build backend
    become: true
    shell : |
        cd /home/ubuntu/web
        npm i
        npm install
        npm run build

  - name: Run server
    become: true
    shell : |
        cd /home/ubuntu/web
        pm2 stop default
        pm2 start npm -- start