---

  - name: Create directory for backend
    file: 
      path: /home/ubuntu/backend
      state: directory

  - name: Copy files
    become: true
    copy:
      src: /home/circleci/project/backend.tar.gz
      dest: /home/ubuntu/backend

  - name: Unarchive backend files
    unarchive:
      src: /home/ubuntu/backend/backend.tar.gz
      dest: /home/ubuntu/backend
      copy: no

  - name: Build backend
    become: true
    shell : |
        cd /home/ubuntu/backend
        npm i
        npm install
        npm run build

  - name: Stop  running servers
    ignore_errors: yes
    shell: |
      pm2 stop backend
      pm2 stop default
      pm2 delete backend

  - name: Run server
    become: true
    shell : |
        cd /home/ubuntu/backend
        pm2 start npm --name backend -- start
        pm2 ls