---

  - name: Create directory for web
    file: 
      path: /home/ubuntu/web
      state: directory

  - name: Copy files
    become: true
    copy:
      src: /root/project/backend.tar.gz
      dest: /home/ubuntu

  - name: Unarchive backend files
    unarchive:
      src: /home/ubuntu/backend.tar.gz
      dest: /home/ubuntu/web
      copy: no

  - name: Start backend
    become: true
    shell: |
      cd /home/ubuntu/web
      npm install
      pm2 stop default
      pm2 start npm -- start
