---
  - name: Update and Upgrade apt
    become: true
    apt: 
      update_cache: yes
      upgrade: 'yes'

  - name: Install nodejs and npm
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes
    
  - name: Install pm2
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Create directory for backend
    file: 
      path: /home/ubuntu/backend
      state: directory

  - name: Copy files
    become: true
    copy:
      src: /home/circleci/project/backend.tar.gz
      dest: /home/ubuntu/backend

  - name: Unarchive backend files
    unarchive:
      src: /home/ubuntu/backend/backend.tar.gz
      dest: /home/ubuntu/backend
      copy: no

  - name: Build backend
    become: true
    shell : |
        cd /home/ubuntu/backend
        npm i
        npm run build

  - name: Run server
    become: true
    shell : |
        cd /home/ubuntu/backend
        pm2 stop default
        pm2 start npm --name backend s-- start

    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"