---

  - name: Create directory for web
    file: 
      path: /home/ubuntu/web
      state: directory

  - name: Copy files
    become: true
    copy:
      src: /root/project/backend.tar.gz
      dest: /home/ubuntu/web

  - name: Unarchive backend files
    unarchive:
      src: /home/ubuntu/web/backend.tar.gz
      dest: /home/ubuntu/web
      copy: no

  - name: Build backend
    become: true
    shell : |
        cd /home/ubuntu/web
        npm i
        npm install
        npm run build

  - name: Run server
    become: true
    shell : |
        cd /home/ubuntu/web
        #pm2 stop default
        #pm2 start npm -- start
        npm run start